name: FTop-Payout
main: me.connectify.ftop.FTop
version: 1.3
author: Connectify
description: Simple plugin for the VailMC Network by Connectify.
commands:
   payout:
    aliases: [setstorecode]

   claimpayout: